// The category tree. Each category becomes /category/[slug].
// Blurbs are plain descriptions of the category, never claims about any business.

export type Category = { slug: string; name: string; blurb: string; group: string };
export type Group = { slug: string; name: string; icon: string; categories: Category[] };

const slugify = (s: string) =>
  s.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const RAW: { name: string; icon: string; items: [string, string][] }[] = [
  {
    name: "Home Services", icon: "Wrench",
    items: [
      ["Plumbers", "Leaks, drains, water heaters and fixture installs."],
      ["Electricians", "Wiring, panels, lighting and safety inspections."],
      ["HVAC", "Heating, cooling and air quality for Utah Valley homes."],
      ["Roofing", "Roof repair, replacement and inspections."],
      ["Landscaping", "Lawn care, design, sprinklers and yard cleanup."],
      ["Lawn Care", "Mowing, fertilizing and seasonal lawn maintenance."],
      ["Snow Removal", "Driveway and lot clearing for Provo winters."],
      ["House Cleaning", "Regular, deep and move-out cleaning."],
      ["Carpet Cleaning", "Carpet, rug and upholstery cleaning."],
      ["Window Cleaning", "Interior and exterior window washing."],
      ["Pest Control", "Insects, rodents and seasonal pest prevention."],
      ["Painters", "Interior and exterior painting."],
      ["Handyman Services", "Small repairs and odd jobs around the house."],
      ["General Contractors", "Remodels, additions and new builds."],
      ["Kitchen and Bath Remodeling", "Kitchen and bathroom renovations."],
      ["Flooring", "Hardwood, tile, carpet and vinyl installation."],
      ["Garage Doors", "Garage door repair, openers and installation."],
      ["Fencing", "Fence building and repair."],
      ["Concrete and Masonry", "Driveways, patios, retaining walls and brickwork."],
      ["Solar Installation", "Residential and commercial solar panels."],
      ["Moving Companies", "Local moves, packing and loading help."],
      ["Junk Removal", "Haul-away for furniture, appliances and cleanouts."],
      ["Locksmiths", "Lockouts, rekeying and lock installation."],
      ["Appliance Repair", "Washers, dryers, refrigerators and ovens."],
      ["Pool and Spa Services", "Pool cleaning, repair and hot tub service."],
      ["Water Damage Restoration", "Flood, fire and mold cleanup."],
    ],
  },
  {
    name: "Food and Drink", icon: "UtensilsCrossed",
    items: [
      ["Restaurants", "Sit-down dining across Provo."],
      ["Cafes and Coffee Shops", "Coffee, tea and a place to sit."],
      ["Bakeries", "Bread, pastries, cakes and custom orders."],
      ["Pizza", "Pizza shops and pizzerias."],
      ["Mexican Restaurants", "Tacos, burritos and regional Mexican food."],
      ["Asian Restaurants", "Chinese, Japanese, Thai, Vietnamese, Korean and more."],
      ["Fast Food", "Quick-service counters and drive-thrus."],
      ["Breakfast and Brunch", "Morning menus and weekend brunch."],
      ["Ice Cream and Desserts", "Ice cream, frozen yogurt, shakes and sweets."],
      ["Juice and Smoothie Bars", "Fresh juices, smoothies and bowls."],
      ["Food Trucks", "Mobile kitchens around Provo."],
      ["Catering", "Food for events, offices and parties."],
      ["Grocery Stores", "Everyday groceries and specialty markets."],
      ["Farmers Markets", "Local produce and seasonal markets."],
      ["Specialty Food Shops", "Butchers, delis, candy and gourmet goods."],
      ["Soda Shops", "Dirty sodas, fountain drinks and Utah classics."],
    ],
  },
  {
    name: "Health and Wellness", icon: "HeartPulse",
    items: [
      ["Dentists", "General, family and cosmetic dentistry."],
      ["Orthodontists", "Braces and aligners."],
      ["Doctors and Clinics", "Primary care, family medicine and walk-in clinics."],
      ["Urgent Care", "Same-day care for non-emergency illness and injury."],
      ["Chiropractors", "Spinal and musculoskeletal care."],
      ["Physical Therapy", "Rehab, injury recovery and mobility."],
      ["Massage Therapy", "Therapeutic and relaxation massage."],
      ["Optometrists", "Eye exams, glasses and contacts."],
      ["Mental Health and Counseling", "Therapy and counseling services."],
      ["Pediatricians", "Medical care for children."],
      ["Pharmacies", "Prescriptions and health supplies."],
      ["Med Spas", "Aesthetic and skin treatments."],
      ["Acupuncture", "Acupuncture and traditional approaches."],
      ["Nutritionists and Dietitians", "Nutrition coaching and meal planning."],
      ["Veterinarians", "Pet medical care."],
    ],
  },
  {
    name: "Beauty and Personal Care", icon: "Scissors",
    items: [
      ["Hair Salons", "Cuts, color and styling."],
      ["Barbershops", "Haircuts and shaves."],
      ["Nail Salons", "Manicures, pedicures and nail art."],
      ["Day Spas", "Facials, wraps and spa treatments."],
      ["Waxing and Hair Removal", "Waxing, sugaring and laser services."],
      ["Tattoo and Piercing", "Tattoo studios and body piercing."],
      ["Makeup Artists", "Makeup for events, weddings and photoshoots."],
      ["Lash and Brow Studios", "Lash extensions and brow shaping."],
      ["Tanning", "Tanning salons and spray tans."],
    ],
  },
  {
    name: "Fitness and Recreation", icon: "Dumbbell",
    items: [
      ["Gyms", "Gyms and fitness centers."],
      ["Yoga and Pilates", "Studios and classes."],
      ["Personal Trainers", "One-on-one and small group training."],
      ["Martial Arts", "Karate, jiu-jitsu, taekwondo and more."],
      ["Climbing Gyms", "Indoor climbing and bouldering."],
      ["Dance Studios", "Dance classes for all ages."],
      ["Outdoor Gear and Rentals", "Ski, bike, camping and paddle gear."],
      ["Bike Shops", "Bike sales, repair and rentals."],
      ["Golf", "Courses, ranges and golf shops."],
      ["Trampoline and Family Fun", "Family entertainment venues."],
      ["Tour Guides and Outfitters", "Guided outdoor trips around Utah Valley."],
    ],
  },
  {
    name: "Auto Services", icon: "Car",
    items: [
      ["Auto Repair", "General mechanical repair and maintenance."],
      ["Oil Change", "Quick lube and routine service."],
      ["Tire Shops", "Tires, alignments and rotations."],
      ["Auto Body and Collision", "Dent, paint and collision repair."],
      ["Car Dealerships", "New and used vehicle sales."],
      ["Car Washes and Detailing", "Washing, detailing and ceramic coating."],
      ["Auto Glass", "Windshield repair and replacement."],
      ["Towing", "Roadside assistance and towing."],
      ["Auto Parts", "Parts and accessories."],
      ["Window Tinting", "Vehicle window tint installation."],
      ["Motorcycle and Powersports", "Sales, repair and gear."],
    ],
  },
  {
    name: "Professional Services", icon: "Briefcase",
    items: [
      ["Accountants and CPAs", "Bookkeeping, tax and accounting."],
      ["Tax Preparation", "Personal and business tax filing."],
      ["Lawyers and Attorneys", "Legal services across practice areas."],
      ["Family Law", "Divorce, custody and family legal matters."],
      ["Estate Planning", "Wills, trusts and probate."],
      ["Real Estate Agents", "Buying, selling and renting homes."],
      ["Property Management", "Rental and HOA management."],
      ["Mortgage Lenders", "Home loans and refinancing."],
      ["Insurance Agents", "Auto, home, life and business insurance."],
      ["Financial Advisors", "Planning, investing and retirement."],
      ["Marketing and SEO Agencies", "Websites, SEO, ads and local marketing."],
      ["Web Design", "Website design and development."],
      ["Photographers", "Portraits, events, real estate and product photography."],
      ["Videographers", "Video production and editing."],
      ["Graphic Design and Printing", "Design, signs, banners and printing."],
      ["Business Consultants", "Strategy, operations and coaching."],
      ["IT Services", "Computer repair, networks and managed IT."],
      ["Staffing and Recruiting", "Hiring and temp staffing."],
      ["Notary and Document Services", "Notary, translation and paperwork help."],
      ["Architects and Designers", "Building and interior design."],
    ],
  },
  {
    name: "Shopping and Retail", icon: "ShoppingBag",
    items: [
      ["Boutiques and Clothing", "Local fashion and clothing stores."],
      ["Gift Shops", "Gifts, cards and local goods."],
      ["Bookstores", "New and used books."],
      ["Furniture Stores", "Furniture and home furnishings."],
      ["Home Decor", "Decor, art and accents."],
      ["Jewelers", "Jewelry sales and repair."],
      ["Florists", "Flowers and arrangements."],
      ["Thrift and Consignment", "Secondhand clothing and goods."],
      ["Sporting Goods", "Equipment and apparel."],
      ["Electronics and Phone Repair", "Devices, repair and accessories."],
      ["Hardware Stores", "Tools, supplies and building materials."],
      ["Craft and Hobby Stores", "Craft, fabric and hobby supplies."],
      ["Toy and Game Stores", "Toys, board games and collectibles."],
      ["Wedding Shops and Bridal", "Dresses, tuxedos and wedding supplies."],
      ["Garden Centers and Nurseries", "Plants, soil and garden supplies."],
    ],
  },
  {
    name: "Education and Kids", icon: "GraduationCap",
    items: [
      ["Tutoring", "Academic tutoring and test prep."],
      ["Music Lessons", "Instrument and voice instruction."],
      ["Preschools and Daycare", "Early childhood education and childcare."],
      ["Private Schools", "Private and charter schools."],
      ["Art Classes", "Art, pottery and creative classes."],
      ["Driving Schools", "Driver education and training."],
      ["Language Schools", "Language classes and ESL."],
      ["Coding and STEM", "Technology and science programs."],
      ["Kids Activities and Camps", "Camps, sports leagues and kid activities."],
      ["Swim Lessons", "Swim instruction for kids and adults."],
    ],
  },
  {
    name: "Events and Entertainment", icon: "PartyPopper",
    items: [
      ["Wedding Venues", "Venues for ceremonies and receptions."],
      ["Event Venues", "Spaces for parties, reunions and corporate events."],
      ["Wedding Planners", "Planning and coordination."],
      ["DJs and Live Music", "Music for events."],
      ["Party Rentals", "Tents, tables, chairs and bounce houses."],
      ["Escape Rooms and Games", "Escape rooms, arcades and game venues."],
      ["Theaters and Performing Arts", "Theater, music and live shows."],
      ["Museums and Attractions", "Local museums and sights."],
      ["Bowling and Mini Golf", "Casual entertainment."],
      ["Wedding Photographers", "Photography for weddings and engagements."],
    ],
  },
  {
    name: "Pets", icon: "PawPrint",
    items: [
      ["Pet Groomers", "Dog and cat grooming."],
      ["Pet Boarding and Daycare", "Kennels, boarding and doggy daycare."],
      ["Dog Training", "Obedience and behavior training."],
      ["Pet Stores", "Food, toys and supplies."],
      ["Dog Walkers and Pet Sitters", "In-home pet care."],
    ],
  },
  {
    name: "Community and Nonprofits", icon: "Users",
    items: [
      ["Nonprofits", "Local charities and community organizations."],
      ["Churches and Faith Communities", "Congregations and places of worship."],
      ["Coworking Spaces", "Shared offices and meeting rooms."],
      ["Libraries and Community Centers", "Public gathering places."],
      ["Senior Care", "Home care, assisted living and senior services."],
      ["Funeral Services", "Funeral homes, cremation and memorial services."],
    ],
  },
  {
    name: "Lodging and Travel", icon: "BedDouble",
    items: [
      ["Hotels", "Hotels and motels."],
      ["Bed and Breakfasts", "Small inns and B&Bs."],
      ["Vacation Rentals", "Short-term home rentals."],
      ["Travel Agencies", "Trip planning and booking."],
      ["Airport Shuttles and Taxis", "Rides and transportation."],
      ["Storage Units", "Self-storage."],
    ],
  },
];

export const groups: Group[] = RAW.map((g) => ({
  slug: slugify(g.name),
  name: g.name,
  icon: g.icon,
  categories: g.items.map(([name, blurb]) => ({ slug: slugify(name), name, blurb, group: slugify(g.name) })),
}));

export const categories: Category[] = groups.flatMap((g) => g.categories);
export const categoryBySlug = (slug: string) => categories.find((c) => c.slug === slug);
export const groupBySlug = (slug: string) => groups.find((g) => g.slug === slug);
